const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),scope=vm.createContext({});
for(const file of ['utils/constants.js','themes/presets.js','themes/character-art.js','themes/collection-art.js','themes/scene-art.js']) vm.runInContext(fs.readFileSync(path.join(root,'extension',file),'utf8'),scope);
const labels={
  'batman':['بتمن','BATMAN · GOTHAM','فیلم','پرواز با شنل، پرتاب بترنگ و روشن شدن نشان خفاش'],
  'star-wars':['جنگ ستارگان','DARTH VADER','فیلم','شمشیر نوری قرمز و موج نیرو روی مربع‌های فعالیت'],
  'harry-potter':['هری پاتر','HARRY POTTER','فیلم','چوب جادو، طلسم طلایی و جرقه‌های نور'],
  'deadpool':['ددپول','DEADPOOL','فیلم','پشتک روی نمودار و دو برش متقاطع کاتانا'],
  'stranger-things':['استرنجر تینگز','ELEVEN · UPSIDE DOWN','سریال','قدرت ذهنی الون، مربع‌های معلق و شکاف دنیای وارونه'],
  'wednesday':['ونزدی','WEDNESDAY & THING','سریال','رقص ونزدی همراه با حرکت دست زنده بین مربع‌ها'],
  'squid-game':['اسکویید گیم','MASKED GUARD','سریال','نگهبان نقاب‌دار، چراغ قرمز و سبز و شکل‌های بازی'],
  'god-of-war':['گاد آو وار','KRATOS · LEVIATHAN','بازی','پرتاب تبر کریتوس، برخورد یخی و بازگشت تبر'],
  'assassins-creed':['اساسینز کرید','EZIO AUDITORE','بازی','پرش از ارتفاع همراه با عبور عقاب روی نمودار'],
  'minecraft':['ماینکرفت','STEVE · OVERWORLD','بازی','کلنگ الماسی استیو، شکستن بلوک و پخش ذرات پیکسلی']
};
const cards=Object.entries(labels).map(([id,[name,character,category,detail]],index)=>{
  const t=scope.VELNAR.getThemeById(id);
  return `<article style="--accent:${t.colors.accent};--base:${t.colors.background}"><div class="portrait">${scope.VELNAR.SceneArt.svg(id)}<span class="number">${String(index+1).padStart(2,'0')}</span><span class="category">${category}</span></div><div class="copy"><span class="character" dir="ltr">${character}</span><h2>${name}</h2><p>${detail}</p><a href="../extension/preview/preview.html?focus=activity#${id}">تماشای انیمیشن <span aria-hidden="true">↗</span></a></div></article>`;
}).join('');
const old=scope.VELNAR.PRESET_THEMES.filter(t=>t.scene&&!labels[t.id]).map(t=>`<a href="../extension/preview/preview.html?focus=activity#${t.id}">${t.name}</a>`).join('');
const html=`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VELNAR 2.4.0 — ده دنیای تازه</title><style>
*{box-sizing:border-box}body{margin:0;background:#080e18;color:#edf1f7;font:14px/1.9 Tahoma,Arial,sans-serif}main{max-width:1680px;margin:auto;padding:36px 32px}header{display:flex;justify-content:space-between;gap:30px;align-items:center;margin-bottom:28px}.brand{display:flex;align-items:center;gap:15px}.brand img{width:46px}.eyebrow{font:11px/1.5 Arial,sans-serif;color:#91b2d4;letter-spacing:2px}h1{font-size:30px;line-height:1.5;margin:6px 0 0}.sub{color:#9aaec7;margin:8px 0 0;font-size:13px}.download{display:inline-flex;gap:14px;align-items:center;background:#b3d2f2;color:#101c2d;padding:12px 22px;border-radius:10px;font-weight:bold;text-decoration:none;white-space:nowrap}.gallery{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:18px}article{border:1px solid #263548;border-radius:15px;overflow:hidden;background:#111b29;transition:border-color .2s}article:hover{border-color:var(--accent)}.portrait{position:relative;height:230px;overflow:hidden;background:var(--base)}.portrait>.vn-art{height:100%;width:auto;max-width:none;position:absolute;left:50%;transform:translateX(-50%)}.portrait:after{content:'';position:absolute;inset:auto 0 0;height:34px;background:linear-gradient(transparent,#111b29)}.number,.category{position:absolute;top:12px;color:var(--accent);background:#080e1899;padding:2px 9px;border:1px solid #ffffff15;border-radius:6px;font-size:10px}.number{left:12px;font-family:Arial}.category{right:12px}.copy{padding:15px 18px 19px}.character{display:block;font:9px/1.6 Arial,sans-serif;letter-spacing:1.4px;color:var(--accent);text-align:right}h2{font-size:19px;margin:4px 0 7px}.copy p{color:#a7b8cd;font-size:12px;min-height:46px;margin:0 0 14px}.copy a{display:flex;justify-content:space-between;color:#ecf4ff;border-top:1px solid #283447;padding-top:11px;font-size:11px;text-decoration:none}.copy a:hover{color:var(--accent)}.prior{display:flex;gap:20px;align-items:center;flex-wrap:wrap;padding:24px 0;color:#93a8bf;font-size:12px}.prior a{color:#c5d6e8;text-decoration:none;font:11px Arial,sans-serif}footer{padding-top:18px;border-top:1px solid #233045;font-size:12px;color:#8e9fb6}.vn-subject{animation:drift 7s ease-in-out infinite}@keyframes drift{50%{transform:translateY(-4px)}}@media(max-width:1200px){.gallery{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:760px){main{padding:24px 14px}header{align-items:flex-start;flex-direction:column;gap:16px}h1{font-size:24px}.gallery{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.portrait{height:210px}.copy{padding:12px}.copy p{min-height:70px}h2{font-size:16px}.character{font-size:8px;letter-spacing:.7px}.sub{font-size:11px}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style></head><body><main><header><div class="brand"><img src="../extension/icons/velnar-mark.svg" alt="VELNAR"><div><span class="eyebrow" dir="ltr">VELNAR / CINEMATIC COLLECTION / 2.4.0</span><h1>ده دنیای تازه، روی گیت‌هاب تو</h1><p class="sub">۱۰ تم جدید + ۵ تم سینمایی قبلی · در مجموع ۴۵ تم قابل انتخاب</p></div></div><a class="download" href="../dist/velnar-extension.zip" download>دانلود نسخهٔ ۲.۴.۰ <span aria-hidden="true">↓</span></a></header><section class="gallery" aria-label="ده تم جدید">${cards}</section><div class="prior"><span>پنج دنیای قبلی هم در مجموعه هستند:</span>${old}</div><footer>برای هر تم، «تماشای انیمیشن» را بزن و از Replay scene استفاده کن. برای نصب، ZIP را استخراج کن؛ سپس پوشه را با Load unpacked بارگذاری کن یا افزونهٔ قبلی را Reload و صفحهٔ GitHub را تازه‌سازی کن.</footer></main></body></html>`;
fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});
fs.writeFileSync(path.join(root,'artifacts/expansion-2.4.0.html'),html);
console.log('Created artifacts/expansion-2.4.0.html');
